version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn tf_idf.wsgi:application --bind 0.0.0.0:${APP_PORT}"
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
